<a href="https://colab.research.google.com/github/Shivam250124/Machine_Learning-/blob/main/feature_selection_using_corr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h3 align="center">Using Correlation For Feature Selection<h3>

In [ ]:
import pandas as pd

df = pd.read_csv("home_prices.csv")
df.head()

   area_sqr_ft  bedrooms color  price_lakhs
0         3774         2   Red          216
1         1460         3  Gray           88
2         1894         4  Gray          147
3         1730         2  Blue           84
4         1695         1  Blue           77

In [ ]:
df.color.unique()

array(['Red', 'Gray', 'Blue', 'Yellow', 'Green', 'White'], dtype=object)

In [ ]:
df_encoded = pd.get_dummies(df, columns=["color"], drop_first=True)
df_encoded.head()

,area_sqr_ft,bedrooms,price_lakhs,color_Gray,color_Green,color_Red,color_White,color_Yellow
0,3774,2,216,False,False,True,False,False
1,1460,3,88,True,False,False,False,False
2,1894,4,147,True,False,False,False,False
3,1730,2,84,False,False,False,False,False
4,1695,1,77,False,False,False,False,False

In [ ]:
cm = df_encoded.corr()
cm

,area_sqr_ft,bedrooms,price_lakhs,color_Gray,color_Green,color_Red,color_White,color_Yellow
area_sqr_ft,1.000000,0.185810,0.945365,-0.068944,-0.032012,0.059055,0.063827,-0.037819
bedrooms,0.185810,1.000000,0.439445,0.040882,-0.120207,-0.004177,-0.023676,0.015286
price_lakhs,0.945365,0.439445,1.000000,-0.040565,-0.041959,0.045803,0.051122,-0.046673
color_Gray,-0.068944,0.040882,-0.040565,1.000000,-0.214409,-0.230990,-0.205931,-0.217205
color_Green,-0.032012,-0.120207,-0.041959,-0.214409,1.000000,-0.190117,-0.169493,-0.178771
color_Red,0.059055,-0.004177,0.045803,-0.230990,-0.190117,1.000000,-0.182600,-0.192596
color_White,0.063827,-0.023676,0.051122,-0.205931,-0.169493,-0.182600,1.000000,-0.171703
color_Yellow,-0.037819,0.015286,-0.046673,-0.217205,-0.178771,-0.192596,-0.171703,1.000000

In [ ]:
cm_price = abs(cm["price_lakhs"])
cm_price

area_sqr_ft     0.945365
bedrooms        0.439445
price_lakhs     1.000000
color_Gray      0.040565
color_Green     0.041959
color_Red       0.045803
color_White     0.051122
color_Yellow    0.046673
Name: price_lakhs, dtype: float64

In [ ]:
selected_features = cm_price[cm_price > 0.2].index.drop("price_lakhs")
selected_features

Index(['area_sqr_ft', 'bedrooms'], dtype='object')

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

X = df[selected_features]
# X = df[["area_sqr_ft", "bedrooms", "color_encoded"]]
y = df['price_lakhs']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a Linear Regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict and evaluate the model
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("R2:", r2, "MSE:", mse)

R2: 0.96894664883796 MSE: 76.63332198278813

Dropping unnecessary features (or doing feature selection) helps in saving compute power. In many cases, it helps in increasing model accuracy and overall performance